# Generated by Django 2.1.7 on 2019-03-27 23:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submit_document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceProvider', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('submit_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('description', models.TextField()),
                ('rajuk', models.FileField(blank=True, null=True, upload_to='submited/files/')),
                ('rajukChk', models.BooleanField(default=False)),
                ('wasa', models.FileField(blank=True, null=True, upload_to='submited/files/')),
                ('bangladeshBank', models.FileField(blank=True, null=True, upload_to='submited/files/')),
                ('titas', models.FileField(blank=True, null=True, upload_to='submited/files/')),
                ('pdb', models.FileField(blank=True, null=True, upload_to='submited/files/')),
                ('accept', models.BooleanField(default=False)),
                ('submitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submitorCm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.CompanyDetails')),
            ],
        ),
    ]
