# Generated by Django 2.1.7 on 2019-03-27 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submit_document',
            name='submitorCm',
        ),
    ]
