# Generated by Django 2.1.7 on 2019-03-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clints', '0002_remove_submit_document_submitorcm'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit_document',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
