# Generated by Django 2.1.7 on 2019-03-28 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clints', '0003_submit_document_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submit_document',
            name='serviceProvider',
        ),
    ]
