# Generated by Django 2.1.7 on 2019-03-28 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProvider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider_submit',
            name='submit_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
